[tool.ruff]
line-length = 79
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 79
extend_skip = ['migrations']

[tool.pytest.ini_options]
pythonpath = "."
minversion = 2.0
norecursedirs = ['.git', '.tox',  'requirements*']
python_files = ['test*.py']
markers = [
    'integration: integration tests'
]

[tool.blue]
extend-exclude = '(migrations/)'

[tool.taskipy.tasks]
lint = 'ruff . && blue --check . --diff'
format = 'blue .  && isort .'
type = 'mypy . --explicit-package-bases'
run = 'uvicorn fast_zero.app:app --reload'
pre_test = 'task lint'
test = 'pytest -s -x --cov=application -vv'
post_test = 'coverage html'