version: '3.8'

services:
  web:
    build:
      context: ${PWD}
      dockerfile: docker/web/Dockerfile.development
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      APPLICATION_DB: ${APPLICATION_DB}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_HOSTNAME: ${MSSQL_HOSTNAME}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PORT: ${MSSQL_PORT}
    command: gunicorn -w 4 -b 0.0.0.0 wsgi:app
    volumes:
      - ${PWD}:/opt/code
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080