version: '3.8'

services:
  api_cad:
    build:
      context: ${PWD}
      dockerfile: docker/web/Dockerfile.production
    environment:
      APPLICATION_DB: ${APPLICATION_DB}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_HOSTNAME: ${MSSQL_HOSTNAME}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PORT: ${MSSQL_PORT}
    command: gunicorn -b :8000 --reload -k uvicorn.workers.UvicornWorker --timeout 500 asgi:app
    volumes:
      - ${PWD}:/opt/code
