version: '3.8'

services:
  sqlserv-cross-selling-test:
    image: mcr.microsoft.com/mssql/server
    user: root
    container_name: sqlserv-cross-selling-test
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_USER: ${MSSQL_USER}
    ports:
      - "${MSSQL_PORT}:1433"
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  #   ports:
  #     - "${MONGODB_PORT}:27017"